target 'iosTest2017' do
platform :ios, '8.0'
pod 'AFNetworking', '~> 3.0'
pod 'Masonry'
pod 'YYCategories'
pod 'CocoaLumberjack'
pod 'SDWebImage'
#pod 'BAWKWebView'
pod 'IQKeyboardManager'
pod 'UITextView+Placeholder'
end

target 'AFNetworkingTest-2017' do
platform :ios, '8.0'
pod 'AFNetworking', '~> 3.0'
end

#如果在Podfile中没有指定target，那么只有工程里的第一个target能够使用Podfile中描述的Pods依赖库。http://blog.csdn.net/wzzvictory/article/details/19178709
target 'MasonryTest' do
    platform :ios, '8.0'
    pod 'Masonry'
    pod 'XMNetworking'
end

target 'TingYunTest' do
    platform :ios, '8.0'
    pod 'tingyunApp', '~> 2.8.2'
#    pod 'tingyunApp'
end

target 'OCTest' do
    platform :ios, '8.0'
    pod 'AvoidCrash', '~> 2.5.2'
end

target 'ThirdLibs-2018' do
    platform :ios, '8.0'
    pod 'Masonry'
    
    pod 'AMap3DMap' #3D地图SDK
#    pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使用)
    pod 'AMapSearch' #搜索功能
    pod 'LBXScan/LBXZXing'
    pod 'LBXScan/UI'
#    pod 'SSZipArchive'
end

target 'SQLiteTest-201603' do
    platform :ios, '8.0'
    pod 'AvoidCrash', '~> 2.5.2'
end


